# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: iranda <marvin@42.fr>                      +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2020/09/28 18:45:19 by iranda            #+#    #+#              #
#    Updated: 2020/09/28 18:48:47 by iranda           ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME	= 	ft_display_file

all:
		gcc -Wall -Werror -Wextra 1.c -o ${NAME}

clean:
		rm -f ${NAME}

fclean:		clean
		rm -f ${NAME}

re:		fclean all
